version: '3.5' 

services: 
    webservice: 
        image: devopsdockeruh/simple-web-service
        volumes: 
        - ../../logs/text.log:/usr/src/app/text.log
        ports: 
            - 8000:8080 
        command: server
