version: '3.5' 

services: 
    frontend: 
        build: ./example-frontend
        ports: 
            - 5000:5000 

    backend:
        build: ./example-backend
        ports: 
            - 8080:8080 
        environment:
            - REDIS_HOST=redis
            - POSTGRES_PASSWORD=pwpwpw
            - POSTGRES_HOST=pg_db
            - POSTGRES_USER=postgres
            - POSTGRES_DATABASE=postgres

    redis:
        image: redis:6.2-alpine
        ports: 
            - 6379:6379

    pg_db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=pwpwpw
        volumes:
            - database:/var/lib/postgresql/data


volumes:
    database: