version: '3.5' 

services: 
    frontend: 
        build: ./example-frontend
        expose: 
            - 5000 
    backend:
        build: ./example-backend
        expose: 
            - 8080 
        environment:
            - REDIS_HOST=redis
            - POSTGRES_PASSWORD=pwpwpw
            - POSTGRES_HOST=pg_db
            - POSTGRES_USER=postgres
            - POSTGRES_DATABASE=postgres
    redis:
        image: redis:6.2-alpine
        expose: 
            - 6379
    pg_db:
        image: postgres:13.2-alpine
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=pwpwpw
        volumes:
            - database:/var/lib/postgresql/data
    nginx:
        image: nginx:stable-alpine
        restart: unless-stopped
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
volumes:
    database: