version: '3.5' 

services: 
    frontend: 
        build: ./example-frontend
        ports: 
            - 5000:5000 

    backend:
        build: ./example-backend
        ports: 
            - 8080:8080 
        environment:
            - REDIS_HOST=redis

    redis:
        image: redis:6.2-alpine
        ports: 
            - 6379:6379
